version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    groups:
      rustcrypto:
        patterns:
          - "hmac"
          - "sha2"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
