[package]
name = "codegen"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
openapiv3 = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
heck = "0.5"
quote = "1.0"
proc-macro2 = "1.0"
indexmap = "2.0"
prettyplease = "0.2"
syn = "2.0"
